# Generated by Django 5.2.12 on 2026-04-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='products_ca_parent__1cafc9_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
